
version: '2'
services:
  keycloak:
    volumes:
      - './data:/opt/jboss/keycloak/standalone/data'
    image: quay.io/keycloak/keycloak:14.0.0
    command: -c standalone.xml
    environment:
      DB_VENDOR: h2
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 8080:8080
      - 8443:8443

